### ISSUE TITLE
Make support_sz part of interp_method

### ISSUE THREAD

**Issue by shaibagon** [assafshocher/ResizeRight#1]
If I understand correctly, `support_sz` is determined by `interp_method`. 
In that case, why not make `support_sz` a [function attribute][1], for example:
```python
@support_sz(4)
def cubic(x):
    fw, to_dtype, eps = set_framework_dependencies(x)
    ...
```
And in the code, you will only need to pass `interp_method` and get the support size from `interp_method.support_sz`
?

---
implementing the decorator:
```python
def support_sz(sz):
     def wrapper(f):
         f.support_sz = sz
         return f
     return wrapper
```

 [1]: https://stackoverflow.com/a/47056146/1714410

**Comment by assafshocher** [comment]
Thanks Shai, that's a great advice! fixed.
