### ISSUE TITLE
Downscale result inconsistent with PIL?

### ISSUE THREAD

**Issue by shaibagon** [assafshocher/ResizeRight#13]
Given a simple input image:
![circle](https://user-images.githubusercontent.com/1818351/177781442-edbaee21-b9d2-4f45-9a3e-8b68b4065c17.png)

When comparing downscaling bicubically by a factor of 8 (from 128 pix to 16), results are inconsistent with PIL and do not look too good:
```
from torchvision import transforms
import resize_right as rr

x = transforms.ToTensor()(pil_img);  # pil_img is a PIL.Image loading the attached circle image
pil_resize = transforms.ToTensor()(pil_img.resize((16,16), Image.Resampling.BICUBIC))
pt_resize = transforms.Resize(size=16, interpolation=transforms.InterpolationMode.BICUBIC,antialias=True)(x).clip(0,1)
rr_resize = rr.resize(x, scale_factors=0.125, interp_method=rr.interp_methods.cubic, antialiasing=False).clip(0,1)
```
This results with the following resized images:
![image](https://user-images.githubusercontent.com/1818351/177782924-e9714ce6-4f34-4206-91a4-a9dbd76d1c0b.png)

As you can see, the output of resize-right has artifacts near the corners, where it shouldn't have.

**Comment by assafshocher** [comment]
Hi Shai! Thanks for this!

1. Can't reproduce. I think the attached image is processed when attached to the text so not identical to original file. Anyway, this is what I get directly from the URL
2.  `response = requests.get('https://user-images.githubusercontent.com/1818351/177781442-edbaee21-b9d2-4f45-9a3e-8b68b4065c17.png')
img = Image.open(BytesIO(response.content))
x = transforms.ToTensor()(img).squeeze(0)
rr_resize = rr.resize(x, scale_factors=0.125, interp_method=rr.interp_methods.cubic, antialiasing=False)
plt.imshow(rr_resize)`
![image](https://user-images.githubusercontent.com/38428604/178088624-140a5b39-c96d-40b5-8e48-713bd331d59e.png)
3.  Nevertheless, I believe the reason for what you see is the fact that rr defaults to zero padding while the others default to 'reflect'. However, rr supports all padding methods of Torch/NumPy so you can `rr.resize(x, ..., pad_mode='constant')`.
4. One other experiment is to take 1-x: so the background value is zero which is the same as the padding.
5. Also I noticed that you used antialaiasing in pt but set False in rr. Not sure why.
6. That said, with antialiasing off and such drastic scale factor, I think padding should not influence. I am not able to reproduce anything that looks like it, even with my own circle.  Are you sure this is actually with antialiasing=False? It looks like a legit result for antialiasing=True.
7. There shouldn't necessarily be consistency with PIL.

**Comment by shaibagon** [comment]
@assafshocher Thanks for the reply.

Here's a code that reproduce the results:
```
import numpy as np
from PIL import Image
from ResizeRight import resize_right as rr
import matplotlib.pyplot as plt
from torchvision import transforms


# generate the circle image
[x, y] = np.meshgrid(np.linspace(-1, 1, 128),np.linspace(-1, 1, 128))
x = np.exp( -((x ** 2) + (y ** 2) - 1)**2 / 0.0025 )
pil_img = Image.fromarray((255 - x*255).astype(np.uint8))

# convert to tensor
x = transforms.ToTensor()(pil_img)

# compare resizing methods
r = [(transforms.ToTensor()(pil_img.resize((16,16), Image.Resampling.BICUBIC)), 'pil_resize'),
     (transforms.Resize(size=16, interpolation=transforms.InterpolationMode.BICUBIC,antialias=True)(x), 'pt_resize'),
     (rr.resize(x, out_shape=(16, 16), interp_method=rr.interp_methods.cubic, antialiasing=True), 'rr_resize')]

# plot
fig, ax = plt.subplots(1,3)
[(a_.imshow(r_[0].clip(0,1).numpy()[0]), a_.set_title(r_[1]))  for a_, r_ in zip(ax.flat, r)]
[(a_.axis('off'), a_.grid(None)) for a_ in ax.flat]
plt.show()
```
It does seem to be related to the padding.

**Comment by assafshocher** [comment]
Thanks!
Okay. So it seems that in your first example, antilaliasing was actually on.
The difference then is the default padding I mentioned before.
Here are the different variants (beginning of the code is identical to yours):

```
  def compare(x):
      # compare resizing methods
      r = [(rr.resize(x, out_shape=(16, 16), interp_method=rr.interp_methods.cubic, antialiasing=True), 'antialiasing=True, \npad_mode="constant"'),
           (rr.resize(x, out_shape=(16, 16), interp_method=rr.interp_methods.cubic, antialiasing=False), 'antialiasing=False, \npad_mode="constant"'),
           (rr.resize(x, out_shape=(16, 16), interp_method=rr.interp_methods.cubic, antialiasing=True, pad_mode='replicate'), 'antialiasing=True, \npad_mode="replicate"'),
           (transforms.Resize(size=16, interpolation=transforms.InterpolationMode.BICUBIC,antialias=True)(x), 'pt_resize_aa_on'),
          (transforms.Resize(size=16, interpolation=transforms.InterpolationMode.BICUBIC,antialias=False)(x), 'pt_resize_aa_off')]
 
      # plot
      fig, ax = plt.subplots(1,5, figsize=(17,7))
      [(a_.imshow(r_[0].clip(0,1).numpy()[0]), a_.set_title(r_[1]))  for a_, r_ in zip(ax.flat, r)]
      [(a_.axis('off'), a_.grid(None)) for a_ in ax.flat]
      plt.show(fig)

  compare(x)
  compare(1-x)
```

![image](https://user-images.githubusercontent.com/38428604/178178277-8ea49fe9-1d4e-4005-82a6-d617e502cdcf.png)


You can see that the result you got is because of padding. However, without AA, the padding has no effect in this case (because the window size for bicubic is 4x4 which is smaller than the receptive field when scaling x0.125. AA stretches that receptive field).
For the 1-x, the zero padding and replicate padding are actually the same, this is why the leftmost result has no padding artifacts.

At the time I considered having default pad_mode='replicate' but decided against it as the natural signal processing common is zero-padding.

Thanks for this!

**Comment by shaibagon** [comment]
@assafshocher Thanks. I think this can close the issue.
