### ISSUE TITLE
BlindSR_dataset_generator related

### ISSUE THREAD

**Issue by zhihongp** [assafshocher/ResizeRight#4]
Sorry to ask this here as the other repo (https://github.com/assafshocher/BlindSR_dataset_generator) is not as active.

Is the DIV2KRK dataset created using BlindSR_dataset_generator, and any tips to reproduce the LR data LR data using saved kernels under gt_k_x4/2, or generate a similar dataset? Like what are `var_max`, `var_min`, and `noise_level` used in generating DIV2KRK kernels?

I have noticed all kernels saved under gt_k_x4 have all-zero borders (3 rows and columns) at bottom-right corner like the example below and wonder if it's caused by `kernel_shift`.  Thanks for your help in advance.

> ...
[1.61147189e-08, 8.95412885e-08, 2.77951758e-07, 9.80985801e-07,
        1.91084409e-06, 4.48469534e-06, 7.12651654e-06, 1.30126017e-05,
        1.83834895e-05, 2.98945272e-05, 3.88450903e-05, 5.32714016e-05,
        6.23909354e-05, 7.37756098e-05, 7.90774956e-05, 8.17760502e-05,
        8.13134218e-05, 7.55632230e-05, 7.01782737e-05, 5.90366766e-05,
        5.11149094e-05, 3.73589671e-05, 2.86220880e-05, 1.69881959e-05,
        1.07876590e-05, 4.31077666e-06, 1.75528828e-06, 4.24068756e-07,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]

**Comment by assafshocher** [comment]
Sorry for the super-late reply.

> Is the DIV2KRK dataset created using BlindSR_dataset_generator,

Yes.

> what are var_max, var_min, and noise_level

The shape of the kernels is non-isotropic gaussian with possible multiplicative noise. Each time you randomly sample a kernel, you sample a rotation angle and also two variances (for the two orthogonal directions). these two variances are sampled uniformly between var_min and var_max.

> I have noticed all kernels saved under gt_k_x4 have all-zero borders (3 rows and columns) at bottom-right corner like the example below and wonder if it's caused by kernel_shift

Yes. kernel-shift would usually be shifting the kernel towards the upper left corner, leaving some zeros at bottom right.
