### ISSUE TITLE
Maybe, there is a typo

### ISSUE THREAD

**Issue by AlanZhang1995** [assafshocher/ResizeRight#5]
Hi,
Thanks for your excellent work.
However, I have some errors using 'resize_right.resize' function. In most of cases, I met 'UnboundLocalError: local variable 'device' referenced before assignment'. But it is not the topic of this issue.

The real thing I want to say is:
I think the line
https://github.com/assafshocher/ResizeRight/blob/master/resize_right.py#L220
should be  `out_shape = (list(out_shape) + list(in_shape[len(out_shape):])` for numpy mode, I guess.

Thank you!

**Comment by shiva811** [comment]
Hey Alan, I am facing the same errors with the "resize_right.resize" function. Were you able to find a way around that?
Thanks in advance!

**Comment by assafshocher** [comment]
Thanks a lot,
This is now fixed.
