### ISSUE TITLE
Bicubic interpolation change image range

### ISSUE THREAD

**Issue by htzheng** [assafshocher/ResizeRight#6]
I notice that ResizeLayer with bicubic interpolation will change the image range, e.g. from [-1,1] to [-1.02, 1.01] with scale_factor=0.5 in my case. However bilinear interpolation won't change the image range.

**Comment by assafshocher** [comment]
This is indeed possible in some interpolation methods. You can clamp it afterwards.
I don't clamp inside the resizer because it should be useful not just for images that are [0,1] and not even preserve the original input range.
